// Selected solved state must drive both shells, not just a mode-chip appearance.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT||path.join(process.env.HOME,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const site=path.join(__dirname,'..'),cwas=path.join(site,'../cwas'),out=path.join(__dirname,'out');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const url=decodeURIComponent(req.url.split('?')[0]);const base=url.startsWith('/cwas/')?cwas:site,relative=url.startsWith('/cwas/')?url.slice(6):url;let file=path.join(base,relative.endsWith('/')?relative+'index.html':relative);if(!file.startsWith(base)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('content-type',file.endsWith('.html')?'text/html':file.endsWith('.svg')?'image/svg+xml':'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,r));const base='http://localhost:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
async function exercise(frame,isSite){
 await frame.waitForFunction(()=>window.circuitEditor&&!circuitEditor.arranging,{}, {timeout:90000});
 if(isSite) await frame.click('[data-host=setup-toggle]');
 await frame.selectOption('#ed-converter','buck');await frame.waitForFunction(()=>!circuitEditor.arranging,{}, {timeout:90000});
 assert(await frame.locator('#ed-model-leakage').isDisabled());assert.match(await frame.locator('#ed-model-leakage').getAttribute('title'),/No coupled windings/);
 const defaultProbe=await frame.evaluate(()=>circuitEditor.probe.id);await frame.click('#ed-model-ideal');assert.equal(await frame.evaluate(()=>circuitEditor.probe.id),defaultProbe);await frame.evaluate(()=>circuitEditor.select('Co'));
 assert.match(await frame.textContent('#ed-model-note'),/no startup/);assert(await frame.locator('#ed-model-view').isDisabled());
 assert(await frame.evaluate(()=>{const before=JSON.stringify(circuitEditor.document);try{circuitEditor.setModel({mode:'invalid'});return false;}catch{return JSON.stringify(circuitEditor.document)===before;}}));
 const components=await frame.evaluate(()=>JSON.stringify(circuitEditor.document.components));
 const inspect=()=>frame.evaluate(()=>{const e=circuitEditor,m=e.model,s=e.sample,d=e.document,c=d.components.find(c=>c.id==='Co'),v=s.state.pressure[m.net['Co.p']]-s.state.pressure[m.net['Co.n']],node=document.querySelector('[data-component="Co"][data-cap-mode]');return {mode:s.metadata.mode,t:e.time,voltage:v,charge:s.state.volumes.Co,current:s.state.currents.L1,travel:+node.dataset.capTravelFraction,expected:s.state.volumes.Co*640000/60*d.settings.travel/57,signal:e.signal.samples.map(s=>s.voltage),plot:document.querySelector('#ed-plots').textContent};});
 const scrub=async(value)=>frame.locator('#ed-scrub').evaluate((n,v)=>{n.value=v;n.dispatchEvent(new Event('input'));},value);
 await scrub(625);const a=await inspect();await scrub(1875);const b=await inspect();assert.equal(a.mode,'ideal');assert.equal(a.voltage,b.voltage);assert.equal(a.charge,b.charge);assert.equal(a.current,b.current);assert(Math.abs(a.travel-a.expected)<1e-10);assert(Math.max(...a.signal)-Math.min(...a.signal)<1e-10);
 await frame.click('#ed-model-ripple');await frame.selectOption('#ed-model-view','settled');await scrub(625);const x=await inspect();await scrub(1875);const y=await inspect();assert.equal(x.mode,'ripple');assert(Math.abs(x.charge-y.charge)>1e-6);assert(Math.abs(x.travel-x.expected)<1e-10);assert(Math.abs(y.travel-y.expected)<1e-10);await scrub(1125);const rising=await inspect();await scrub(2375);const falling=await inspect();assert(Math.abs(rising.current-falling.current)>.3);assert(Math.max(...x.signal)-Math.min(...x.signal)>.1);assert(await frame.locator('#ed-plots path[opacity="0.22"]').count()>0);
 await frame.check('#ed-model-overlay');assert.match(await frame.textContent('#ed-plots'),/Dashed: periodic course reference/);assert.equal(await frame.evaluate(()=>circuitEditor.sample.metadata.mode),'ripple');await frame.uncheck('#ed-model-overlay');
 assert.equal(await frame.evaluate(()=>JSON.stringify(circuitEditor.document.components)),components);
 if(isSite){assert.match(await frame.textContent('[data-host=levels]'),/converged PWM cycles/);assert.match(await frame.textContent('[data-host=levels]'),/ΔV/);await page.screenshot({path:path.join(out,'modes-buck-desktop.png')});}
 await frame.selectOption('#ed-converter','flyback');await frame.waitForFunction(()=>!circuitEditor.arranging,{}, {timeout:90000});await frame.selectOption('#ed-model-view','startup');
 const documentBefore=await frame.evaluate(()=>({components:circuitEditor.document.components,wires:circuitEditor.document.wires}));
 await scrub(7605);const baseline=await frame.evaluate(()=>{const s=circuitEditor.sample,n=circuitEditor.model.net;return s.state.pressure[n['T1.p1']]-s.state.pressure[n['T1.n1']];});
 await frame.click('#ed-model-leakage');await scrub(7605);
 const leak=await frame.evaluate(()=>{const e=circuitEditor,s=e.sample,n=e.model.net;return {mode:s.metadata.mode,voltage:s.state.pressure[n['T1.p1']]-s.state.pressure[n['T1.n1']],painted:+document.querySelector('[data-winding="1"]').dataset.windingVoltage,equivalent:e.model.metadata.equivalent,doc:{components:e.document.components,wires:e.document.wires}};});
 assert.equal(leak.mode,'leakage');assert(Math.abs(leak.voltage-baseline)>.1);assert(Math.abs(leak.voltage-leak.painted)<1e-9);assert.equal(leak.equivalent.length,1);assert.deepEqual(leak.doc,documentBefore);assert.match(await frame.textContent('#ed-model-equivalent'),/Rsnub → Csnub/);
 const perf=await frame.evaluate(()=>{const node=document.querySelector('#ed-scrub'),times=[];for(let j=0;j<30;j++){node.value=7500+j*4;const t=performance.now();node.dispatchEvent(new Event('input'));times.push(performance.now()-t);}times.sort((a,b)=>a-b);return {median:times[15],p95:times[28]};});assert(perf.p95<75,JSON.stringify(perf));console.log(isSite?'site':'editor','leakage paint ms',perf);
 await frame.click('#ed-undo');assert.equal(await frame.evaluate(()=>circuitEditor.sample.metadata.mode),'ripple');await frame.click('#ed-redo');assert.equal(await frame.evaluate(()=>circuitEditor.sample.metadata.mode),'leakage');
 const saved=await frame.evaluate(()=>JSON.stringify(circuitEditor.document));await frame.evaluate(json=>circuitEditor.load(JSON.parse(json)),saved);assert.equal(await frame.evaluate(()=>JSON.stringify(circuitEditor.document)),saved);
 if(isSite){await frame.locator('.model-details>summary').click();await page.screenshot({path:path.join(out,'modes-flyback-protection.png')});await frame.locator('.model-details>summary').click();}
 await frame.selectOption('#ed-converter','forward');await frame.waitForFunction(()=>!circuitEditor.arranging,{}, {timeout:90000});await frame.evaluate(()=>{const d=circuitEditor.document;d.components.find(c=>c.id==='Q1').pwm.duty=.6;circuitEditor.load(d);});assert(!(await frame.locator('#ed-model-ideal').isDisabled()));assert(await frame.locator('#ed-model-leakage').isDisabled());assert.match(await frame.textContent('#ed-model-note'),/reset invalid/);
 await frame.selectOption('#ed-converter','fullbuck');await frame.waitForFunction(()=>!circuitEditor.arranging,{}, {timeout:90000});assert(!(await frame.locator('#ed-model-ideal').isDisabled()));assert(await frame.locator('#ed-model-leakage').isDisabled());assert.match(await frame.textContent('#ed-model-note'),/Ripple/);
 await frame.click('#ed-model-ideal');assert.equal(await frame.evaluate(()=>circuitEditor.sample.metadata.mode),'ideal');assert.equal(await frame.evaluate(()=>circuitEditor.sample.metadata.reduced),false);assert(!(await frame.locator('#ed-model-view').isDisabled()));assert.match(await frame.textContent('#ed-model-note'),/No validated ripple-neglected reduction/);await scrub(1250);assert(await frame.evaluate(()=>{const e=circuitEditor,n=e.model.net,s=e.sample;return Math.abs(+document.querySelector('[data-winding="1"]').dataset.windingVoltage-(s.state.pressure[n['T1.p1']]-s.state.pressure[n['T1.n1']]))<1e-9;}));
 await frame.evaluate(()=>{const d=circuitEditor.document;d.components.push({id:'Extra',type:'resistor',value:10,x:100,y:100,rotation:0});circuitEditor.load(d);});assert.equal(await frame.evaluate(()=>circuitEditor.modeSupport.topology),'custom');assert(!(await frame.locator('#ed-model-ideal').isDisabled()));
}
try{await page.goto(base+'/app/');await exercise(page,true);await page.click('[data-host=setup-close]');await page.setViewportSize({width:390,height:844});await page.click('[data-dock=simulation]');await page.selectOption('#ed-converter','buck');await page.waitForFunction(()=>!circuitEditor.arranging,{}, {timeout:90000});await page.click('#ed-model-ideal');assert(await page.locator('#ed-model-ideal').isVisible());const width=await page.evaluate(()=>({body:document.documentElement.scrollWidth,window:innerWidth}));assert(width.body<=width.window+1,JSON.stringify(width));await page.screenshot({path:path.join(out,'modes-phone.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/cwas/simulator/circuit-editor.html');const frame=page.frames().find(f=>f!==page.mainFrame());assert(frame);await exercise(frame,false);assert.deepEqual(errors,[]);console.log('Both shells: selected solved values drive charge wall and winding pressure; overlay, mode guards, undo/save/load, performance, desktop and phone passed.');}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exit(1)});
